[package]
name = "egor00f/stdlib"
description = "Library that implements some algorithms"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
repository = "https://github/Ukuroks-games/stdlib"
authors = ["Egor00f <velikiydolbayeb@gmail.com>"]
exclude = ["stdlib.rbxl", "stdlib.project.json", "tests"]
private = false


[dev-dependencies]
testlib = "egor00f/testlib@0.1.4"


[place]
shared-packages = "game.ReplicatedStorage.Packages"
