[package]
name = "egor00f/stdlib"
description = "Library that implements some algorithms"
version = "0.1.13"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
repository = "https://github/Ukuroks-games/stdlib"
authors = ["Egor00f <velikiydolbayeb@gmail.com>"]
private = false


[dev-dependencies]
testlib = "egor00f/testlib@>=1.0.1"


[place]
shared-packages = "game.ReplicatedStorage.Packages"
