name: Lint

on:
  release:
    types: [
      published
    ]

jobs:
  Publish:
    name: Publish wally package
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Publish
        run: wally publish
